config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :categoria
  resources :sobres
  get 'users/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :path_prefix => 'd'
resources :users, :only =>[:show]
match '/users',   to: 'users#index',   via: 'get'
match '/users/:id',     to: 'users#show',       via: 'get'

  resources :articles do
  resources :comments
end
resources :comments
    root to: 'articles#index'

resources :tags
end

app/models/article.rb
class Article < ApplicationRecord

has_many :comments
has_many :taggings, dependent: :delete_all
has_many :tags, through: :taggings, dependent: :delete_all
has_attached_file :image
validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

def tag_list
  self.tags.collect do |tag|
    tag.name
  end.join(", ")
end

def tag_list=(tags_string)
tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
 new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  self.tags = new_or_found_tags
end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
include ArticlesHelper
#before_action :authenticate_user!
    def index
        @article = Article.all
    end
    def show
        @article = Article.find(params[:id])
        @comment = Comment.new
        @comment.article_id = @article.id
    end
    def new
        @article = Article.new
    end
    def create
        @article = Article.new(article_params)
        @article.autor = current_user.username
        @article.save
flash.notice = "Article '#{@article.title}' created!"
  redirect_to article_path(@article)
    end
    def destroy
        @article = Article.find(params[:id]).destroy
        flash.notice = "Article '#{@article.title}' deleted!"
        redirect_to action: "index"
    end
    def edit
        @article = Article.find(params[:id])
    end
    def update
        @article = Article.find(params[:id])
        @article.update(article_params)

        flash.notice = "Article '#{@article.title}' Updated!"

        redirect_to article_path(@article)
end
end

app/helpers/articles_helper.rb
module ArticlesHelper
def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end
end

app/views/articles/_comment.html.erb
<div>
  <h4>Comentário por <%=link_to comment.author_name, user_path(comment.author_name) %></h4>
  <p class="comment"><%= raw comment.body %></p>


<% if user_signed_in? %>
<% if current_user.username == comment.author_name or current_user.admin? %>
<%= link_to 'Excluir', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Tem certeza?' } %>
<%= link_to 'Edit', edit_article_comment_path(@article, comment) %>
<% end %><% end %>
</p>
</div>

app/views/articles/_form.html.erb
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :Título %><br />
    <div  ><%= f.text_field :title %></div>

  </p>
<p>
  <%= f.label :Categoria %><br />
  <%= f.text_field :tag_list %>
</p>
  <p>
    <%= f.label :Texto %><br />
    <%= f.cktext_area :body %>
  </p>
  <p>
    <%= f.submit "Enviar", :class=>"waves-effect waves-light btn" %>
  </p>

<p>
  <% if @article.image.exists? %>
      <%= image_tag @article.image.url %><br/>
  <% end %>
  <%= f.label :image, "Anexar imagem" %><br />
  <%= f.file_field :image %>
</p>

<% end %>

app/views/articles/edit.html.erb
<h1 class="center">Editar um artigo</h1>
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1 class="center">Todos os artigos</h1>

<br /><br />


<% if user_signed_in? %>
<p class="center"><%= link_to "Novo artigo", new_article_path, class: "new_article", :class=>"waves-effect waves-light btn" %></p>
<% end %>


<br /><br />

        <table>
            <thead>
            <tr>
                <th colspan="3"></th>
            </tr>
        </thead>

  <tbody>

        <div id="articles">
          <% @article.each do |article| %>
          </div>

          <tr>
              <hr width=60%> <li class="center"  ><font size="5">
          <%= link_to article.title, article_path(article),class: 'article_title', id: "article_#{article.id}" %>
            </font></li></hr>
                  </tr>
                <% end %>
</tbody>
</table>

</br></br></br></br></br></br></br></br></br></br></br></br></br></br></br></br>

app/views/articles/new.html.erb
<%= link_to "<< Retornar ", articles_path, :class=>"waves-effect waves-light btn"  %>
<br /><br /><br />
<h1 class="center">Criar novo artigo</h1>
<%= render partial: 'form' %>

app/views/articles/show.html.erb
<%= link_to "<< Retornar ", articles_path, :class=>"waves-effect waves-light btn" %> <br \><br \><br \>
<p>
<% if user_signed_in? %>
<%= link_to "Excluir", article_path(@article), method: :delete,data: {confirm: "Realmente deseja excluir esse artigo?"}, :class=>"waves-effect waves-light btn"  %>
<%= link_to "Editar", edit_article_path(@article), :class=>"waves-effect waves-light btn"  %>
<% end %>
</p>

</br></br></br>

<h1 class="center"><%= @article.title %></h1>
Criado dia <%= @article.created_at.strftime("%d %b, %Y") %> por <%= link_to @article.autor,user_path(@article.autor) %>


<p>

        Categorias:
        <% @article.tags.each do |tag| %>
          <div class="chip"><fornt size="5"><%= link_to tag.name, tag_path(tag) %></font></div>
        <% end %>

</p>

<div class=" grey lighten-2"><%= raw @article.body %></div></br></br>

 <% if @article.image.exists? %>
    <%= image_tag @article.image.url %>
<% end %>


<h3>Comentários (<%= @article.comments.size %>)</h3>
<%= render partial: 'articles/comment', collection: @article.comments.reverse %>

<p>

</br></br></br>
<% if user_signed_in? %>

            <% if current_user.username == @article.autor or current_user.admin? %>


            <h3>Postar comentário</h3>
            <%= render partial: 'comments/form' %></br></br>
            <% if current_user.username == @article.autor or current_user.admin? %>
<% else %>
É necessário estar logado para comentar
            <% end %>
<% end %>
<% end %>
</p>