config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :categoria
  resources :sobres
  get 'users/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :path_prefix => 'd'
resources :users, :only =>[:show]
match '/users',   to: 'users#index',   via: 'get'
match '/users/:id',     to: 'users#show',       via: 'get'

  resources :articles do
  resources :comments
end
resources :comments
    root to: 'articles#index'

resources :tags
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login
     def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
    end
    validates :username, :presence => true, :uniqueness => {:case_sensitive => false}

    validate :validate_username

    def validate_username
        if User.where(email: username).exists?
     errors.add(:username, :invalid)
    end

end
has_many :articles, foreign_key: :author_id
has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
  def index
    @user = User.all

  end
def show
    @article = Article.new
  @user = User.find_by_username(params[:id])

end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1 class="center">Usuários:</h1></br></br>
<% @users = User.all %>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

<tbody>

<% @users.each do |user| %>

<tr>
              <hr width=60%> <li class="center"  ><font size="5">
                <%= link_to user.username, user_path(user.username) %></font></li></hr>
</tr>


<% end %>

</tbody>
</table>

</br></br></br></br></br></br></br></br></br></br></br></br>

app/views/users/show.html.erb
<ul >
<% if current_user.username == @user.username %><%= link_to 'Editar perfil', edit_user_registration_path , :class => 'waves-effect waves-light btn'%><% end %>
<%= link_to "<< Retornar para todos usuários:", users_path, :class => 'waves-effect waves-light btn' %>
</ul><br/><br/>

<h1 class="center"><%= @user.username %></h1></br>
<p class="center"><%= image_tag(@user.avatar.url(:thumb)) %></p></br>
<font size="5" >Nome: <%= @user.name %></fornt><br/>
Email:  <%= @user.email %><br/>
Nascimento: <% if @user.date_of_birth != nil %><%= @user.date_of_birth.to_date.strftime("%d /%m/ %Y") %> <br/><br/><% end %>

<% @article = Article.all %>


<h3 class="center">Artigos criados pelo usuário:</h3>
<% @article.each do |article| %>
<% if @user.username == article.autor %>
    <ul class="center"><li><%= link_to article.title, article_path(article),
    class: 'article_title', id: "article_#{article.id}" %>
    </li>
  <% end %></ul>
<% end %>