config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :categoria
  resources :sobres
  get 'users/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :path_prefix => 'd'
resources :users, :only =>[:show]
match '/users',   to: 'users#index',   via: 'get'
match '/users/:id',     to: 'users#show',       via: 'get'

  resources :articles do
  resources :comments
end
resources :comments
    root to: 'articles#index'

resources :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :taggings,dependent: :destroy

  has_many :articles, through: :taggings

  def to_s
    name
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
def index 
@tag = Tag.all
end
def show
  @tag = Tag.find(params[:id])
end
def destroy
        @tag = Tag.find(params[:id])
        @tag.destroy
flash.notice = "Tag '#{@tag.name}' deleted!"
        redirect_to action: "index"
    end
   
    def update
        @tag = Tag.find(params[:id])
        @tag.update(tag_params)

        flash.notice = "Tag '#{@tag.name}' Updated!"

        redirect_to tag_path(@tag)
end


end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/index.html.erb
<h1 class="center">Todas as categorias</h1></br></br>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>


<tbody>
<ul id="tag">

  <% @tag.each do |tag| %>
    <tr>
              <hr width=60%> <li class="center"  ><font size="5">
                         <%= link_to tag.name,tag_path(tag) %>
    </font></li></hr>
      </tr>
  <% end %>
</ul>
</tbody>
</table>

</br></br></br></br></br></br>
</br>
</br>

app/views/tags/show.html.erb
<%= link_to "<< Retornar", tags_path, :class => 'waves-effect waves-light btn' %>
<%= link_to "Excluir", tag_path(@tag), method: :delete,data: {confirm: "Realmente deseja excluir essa categoria?"}, :class => 'waves-effect waves-light btn'%>


</br></br></br></br>
<h1 class="center">Artigos com a categoria <%= @tag.name %></h1></br></br>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

<tbody>


  <% @tag.articles.each do |article| %>
    <tr>
              <hr width=60%> <li class="center"  ><font size="5">
              <%= link_to article.title, article_path(article) %></font></li></hr>
      </tr>

  <% end %>

</tbody>
</table>

</br></br></br></br></br></br></br></br></br></br></br></br></br>
</br>