config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :categoria
  resources :sobres
  get 'users/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :path_prefix => 'd'
resources :users, :only =>[:show]
match '/users',   to: 'users#index',   via: 'get'
match '/users/:id',     to: 'users#show',       via: 'get'

  resources :articles do
  resources :comments
end
resources :comments
    root to: 'articles#index'

resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

has_many :comments
has_many :taggings, dependent: :delete_all
has_many :tags, through: :taggings, dependent: :delete_all
has_attached_file :image
validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

def tag_list
  self.tags.collect do |tag|
    tag.name
  end.join(", ")
end

def tag_list=(tags_string)
tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
 new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  self.tags = new_or_found_tags
end

end

app/models/categoria.rb
class Categoria < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/sobre.rb
class Sobre < ApplicationRecord
end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :taggings,dependent: :destroy

  has_many :articles, through: :taggings

  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article

end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login
     def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end
    end
    validates :username, :presence => true, :uniqueness => {:case_sensitive => false}

    validate :validate_username

    def validate_username
        if User.where(email: username).exists?
     errors.add(:username, :invalid)
    end

end
has_many :articles, foreign_key: :author_id
has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
include ArticlesHelper
#before_action :authenticate_user!
    def index
        @article = Article.all
    end
    def show
        @article = Article.find(params[:id])
        @comment = Comment.new
        @comment.article_id = @article.id
    end
    def new
        @article = Article.new
    end
    def create
        @article = Article.new(article_params)
        @article.autor = current_user.username
        @article.save
flash.notice = "Article '#{@article.title}' created!"
  redirect_to article_path(@article)
    end
    def destroy
        @article = Article.find(params[:id]).destroy
        flash.notice = "Article '#{@article.title}' deleted!"
        redirect_to action: "index"
    end
    def edit
        @article = Article.find(params[:id])
    end
    def update
        @article = Article.find(params[:id])
        @article.update(article_params)

        flash.notice = "Article '#{@article.title}' Updated!"

        redirect_to article_path(@article)
end
end

app/controllers/sobres_controller.rb
class SobresController < ApplicationController
  before_action :set_sobre, only: [:show, :edit, :update, :destroy]

  # GET /sobres
  # GET /sobres.json
  def index
    @sobres = Sobre.all
  end

  # GET /sobres/1
  # GET /sobres/1.json
  def show
  end

  # GET /sobres/new
  def new
    @sobre = Sobre.new
  end

  # GET /sobres/1/edit
  def edit
  end

  # POST /sobres
  # POST /sobres.json
  def create
    @sobre = Sobre.new(sobre_params)

    respond_to do |format|
      if @sobre.save
        format.html { redirect_to @sobre, notice: 'Sobre was successfully created.' }
        format.json { render :show, status: :created, location: @sobre }
      else
        format.html { render :new }
        format.json { render json: @sobre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sobres/1
  # PATCH/PUT /sobres/1.json
  def update
    respond_to do |format|
      if @sobre.update(sobre_params)
        format.html { redirect_to @sobre, notice: 'Sobre was successfully updated.' }
        format.json { render :show, status: :ok, location: @sobre }
      else
        format.html { render :edit }
        format.json { render json: @sobre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sobres/1
  # DELETE /sobres/1.json
  def destroy
    @sobre.destroy
    respond_to do |format|
      format.html { redirect_to sobres_url, notice: 'Sobre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sobre
      @sobre = Sobre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sobre_params
      params.fetch(:sobre, {})
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
def index 
@tag = Tag.all
end
def show
  @tag = Tag.find(params[:id])
end
def destroy
        @tag = Tag.find(params[:id])
        @tag.destroy
flash.notice = "Tag '#{@tag.name}' deleted!"
        redirect_to action: "index"
    end
   
    def update
        @tag = Tag.find(params[:id])
        @tag.update(tag_params)

        flash.notice = "Tag '#{@tag.name}' Updated!"

        redirect_to tag_path(@tag)
end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
  def index
    @user = User.all

  end
def show
    @article = Article.new
  @user = User.find_by_username(params[:id])

end
end

app/helpers/application_helper.rb
module ApplicationHelper
module ApplicationHelper
  def flash_message
    messages = ""
    [:notice, :info, :warning, :error].each {|type|
      if flash[type]
        messages += "<p class=\"#{type}\">#{flash[type]}</p>"
      end
    }

    messages
  end
end
end

app/helpers/articles_helper.rb
module ArticlesHelper
def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sobre_helper.rb
module SobreHelper
end

app/helpers/sobres_helper.rb
module SobresHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Portal Educa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body>
   <nav>

          <div class="nav-wrapper light-blue">
            <a href="http://localhost:3000/articles" class="brand-logo" >PORTAL EDUCA</a>
            <ul class="right hide-on-med-and-down">

            <%= link_to 'Categorias', categoria_path, :class => 'waves-effect waves-light btn'%>
            <% if user_signed_in? %>
              <%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'waves-effect waves-light btn'  %><% end %>
            <% if user_signed_in? == false %>
              <%= link_to "Cadastrar-se", new_user_registration_path, :class => 'waves-effect waves-light btn'  %> |
              <%= link_to "Entrar", new_user_session_path, :class => 'waves-effect waves-light btn'  %> <% end %>

            <% @users = User.all %>
            <% @users.each do |user| %>

        <% if user_signed_in? %>
          <% if current_user.username == user.username %>
             <li><a><%= link_to user.username, user_path(user.username), :class => 'waves-effect waves-light btn' %> </a></li>
            <% if current_user.admin? %>
            <%= link_to 'Admin panel', rails_admin_path, :class => 'waves-effect waves-light btn'%>
            <% end %>
          <% end %>

        <% else %>

        <% end %>
          <%end%>

        </ul>
        </div>
         </nav>


        <div class="container">
         <p class="navbar-text pull-right"></p>
         <% if flash[:notice] %>
          <p class="alert"><%= flash[:notice] %></p>
          <% end %>
          <% if flash[:alert] %>
          <p class="alert"><%= flash[:alert] %></p>
              <% end %></p>
            <%= yield %>
        <p class="flash"><%= flash.notice %></p>
        </div>

  </body>
      <footer class="page-footer light-blue">
          <div class="container">
            <div class="row">
              <div class="col l6 s12">
                <h5 class="white-text">Contatos :</h5>
                <p class="grey-text text-lighten-4">Emails: Joberth.rogers18@gmail.com /ebmm01@gmail.com
</p>
                <p class="grey-text text-lighten-4">Telefones: (61)3546-9347 / (XX)XXXXX-XXXX</p>
              </div>

            </div>
          </div>
          <div class="footer-copyright">
            <div class="container">
            © Portal Educa
                        <ul class="right hide-on-med-and-down">
                        <a class="grey-text text-lighten-4 right" href="#!"><%= link_to 'Sobre', sobres_path, :class => 'waves-effect waves-light btn'%></a>
                          </ul >
            </div>
          </div>
        </footer>

</html>